### PR TITLE
Support for Windows

### PR DESCRIPTION
**Pull request by judahr**
Support for windows:  moves some strings to config so windows can be supported.  Also fixed the command line arguments as they weren't working for windows, but should still work for other OS.  The kill command won't work for windows unless homebridge process is under an admin account.  Leaving that one blank seems to be fine through restarts.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Looks good, thanks very much for this addition.  Could you also update the README.md with new configuration options ?

**Comment by judahr** [comment]
ok, updated the readme.

**Comment by NorthernMan54** [comment]
Tks going to merge this, do some regression testing, then publish to npm.

Thank you for this update

**Comment by NorthernMan54** [comment]
And it has been published to npm

**Pull request merged**
